### PR TITLE
[#575] Set default port for MariaDB

### LINKED ISSUE #575: Default port not set for MariaDB
When the URL for MariaDB doesn't contain the port we don't set the default value.
I also noticed that the build get stuck if a test fails during the setup.

I have a fix almost ready.

### PR DESCRIPTION
**Pull request by DavideD**
Fixes #575 

This also throws an exception now if we don't have a default port for the scheme in the URI.

@gavinking I've noticed we still have the class [UriPoolConfiguration](https://github.com/hibernate/hibernate-reactive/blob/master/hibernate-reactive-core/src/test/java/org/hibernate/reactive/UriPoolConfiguration.java) around.

I don't think we are using it now and if I remember correctly we plan to use it when they added some changes in Vert.x.
I'm wondering if we should remove it for now or at least add a Javadoc to it.

### CODE REVIEW

**Comment by gavinking** [comment]
> I'm wondering if we should remove it for now or at least add a Javadoc to it.

well, no, we don't want to remove it, it's part of the test for the `hibernate.vertx.pool.configuration_class` setting.

File: hibernate-reactive-core/src/test/java/org/hibernate/reactive/BaseReactiveTest.java [hunk 1]
```diff
@@ -141,9 +141,14 @@ public void before(TestContext context) {
 
 		final Async async = context.async();
 		Handler<AsyncResult<org.hibernate.SessionFactory>> result = r -> {
```
Comment (gavinking) [inline hibernate-reactive-core/src/test/java/org/hibernate/reactive/BaseReactiveTest.java:143]: Must say I'm not at all a fan of the assigning-an–anonymous-function-to-a-local-variable idiom. I would inline this local. But that's orthogonal to this patch.

**Review by gavinking — APPROVED** [review]
LGTM

**Comment by DavideD** [comment]
Sorry, my bad

> > I'm wondering if we should remove it for now or at least add a Javadoc to it.
> 
> well, no, we don't want to remove it, it's part of the test for the `hibernate.vertx.pool.configuration_class` setting.

RIght, I didn't realize it was in the test folder.

**Comment by DavideD** [comment]
Merged https://github.com/hibernate/hibernate-reactive/pull/576
