### PR TITLE
[4.2] Prevent context switching during id generation

### LINKED ISSUE #2768: A connection can be opened in the wrong Context
Follows https://github.com/hibernate/hibernate-reactive/pull/2690

@tsegismont  [already provided solution](https://github.com/hibernate/hibernate-reactive/pull/2690#issuecomment-3513163421) but it needs to be converted into a proper fix for Hibernate Reactive.

### PR DESCRIPTION
**Pull request by DavideD**
Fix #2768 

Follows https://github.com/hibernate/hibernate-reactive/pull/2690 and it's a refactoring of @tsegismont [suggestion](https://github.com/hibernate/hibernate-reactive/pull/2690#issuecomment-3513163421).

* I changed the warning about the swithching context into [assertions](https://github.com/hibernate/hibernate-reactive/commit/9dce31a9a503b8a3f3ac5189540677da7c41b799#diff-a3210bb1373db55b4feb0d8c4031314d1117c6747351f5cd267f8cc65ab8ab63R350:~:text=InternalStateAssertions%2EassertCurrentContextMatches%28%20this%2C%20connectionContext%20%29%3B)
* I had to change where we read the context when a new connection is created. The problem is that the session factory can be used in a worker thread at start up, and therefore the context could be null. [This is the line that saves the context](https://github.com/hibernate/hibernate-reactive/compare/main...DavideD:hibernate-reactive:2768-Connection-context#diff-9aa5cbca30d703f6ba7e72d257b7e5a9acf0ef42035f1787ab3743aba45137deR226:~:text=newConnection)
* [ProxyConnection](https://github.com/DavideD/hibernate-reactive/blob/e4fdfd4e99f0158f365f67d15816566f47c58d21/hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/SqlClientPool.java#L233) synchronize the creation of a connection using reflection. I don't know if this can be a problem with Quarkus.

### CODE REVIEW

File: hibernate-reactive-core/src/main/java/org/hibernate/reactive/common/InternalStateAssertions.java [hunk 1]
```diff
@@ -52,4 +54,13 @@ public static void assertCurrentThreadMatches(Thread expectedThread) {
 		}
 	}
 
+	public static void assertCurrentContextMatches(Object object, ContextInternal expectedContext, Exception creationTrace) {
```
Comment (yrodiere) [inline hibernate-reactive-core/src/main/java/org/hibernate/reactive/common/InternalStateAssertions.java]: With this new assertion, do we still need `assertCurrentThreadMatches`? If not, fixing #2736 would be trivial...

File: hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/SqlClientPool.java [hunk 2]
```diff
@@ -123,12 +125,18 @@ public CompletionStage<ReactiveConnection> getConnection(String tenantId, SqlExc
 	}
 
 	private CompletionStage<ReactiveConnection> getConnectionFromPool(Pool pool) {
-		return completionStage( pool.getConnection().map( this::newConnection ), ReactiveConnection::close );
+		final Exception creationTrace = new Exception();
```
Comment (yrodiere) [inline hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/SqlClientPool.java]: This is something I wouldn't have done out of concern performance would be bad.

Is this wise?
Is it already done elsewhere?

At the very least I'd avoid creating this exception if `InternalStateAssertions.ENFORCE` is `false`. Though that won't help Quarkus.

File: hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/SqlClientPool.java [hunk 3]
```diff
@@ -205,18 +213,38 @@ private <T> CompletionStage<T> completionStage(Future<T> future, Consumer<T> onC
...
 	}
 
 	private static class ProxyConnection implements ReactiveConnection {
+
+		private static final VarHandle OPENED_HANDLE;
+
+		static {
+			try {
+				MethodHandles.Lookup lookup = MethodHandles.lookup();
+				OPENED_HANDLE = lookup.findVarHandle( ProxyConnection.class, "opened", boolean.class );
```
Comment (yrodiere) [inline hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/SqlClientPool.java:241]: This is new to me, but it looks like a common pattern in `CompletableFuture`. I guess the idea is to get access to `compareAndSet` without the overhead of `AtomicBoolean`. Whether this overhead is significant in this specific case is quite questionable if you ask me, but I assume Thomas knows better than I do. 

In any case, back to your question @DavideD: this kind of "reflection" in a `static` block should generally be fine in Quarkus even with native compilation, because it's executed during static init, before native compilation. If I turn out to be wrong, we'll improvise :)

File: hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/SqlClientPool.java [hunk 4]
```diff
@@ -356,13 +390,8 @@ public CompletionStage<Void> rollbackTransaction() {
...
-			if ( connection == null ) {
-				this.batchSize = batchSize;
-			}
-			else {
-				connection = connection.withBatchSize( batchSize );
-			}
+		public ProxyConnection withBatchSize(int batchSize) {
+			connectionFuture.thenApply( reactiveConnection -> reactiveConnection.withBatchSize( batchSize ) );
 			return this;
 		}
```
Comment (yrodiere) [inline hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/SqlClientPool.java]: This seems wrong?

The method is supposed to return a batched connection, and from what I can see we rely on the return value:

https://github.com/hibernate/hibernate-reactive/blob/066917f1b35c39b81ddfd3793ea75336cd418220/hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/impl/ReactiveSessionImpl.java#L1753-L1757

Returning `this` will not work because we don't update the delegate, so if the caller uses `this`, they'll still be using a non-batching connection.

I'll assume the contract is that `this` can be ignored after this method is called, and only the return value will be used by the caller. Which seems consistent with what I'm seeing in `BatchedConnection#withBatchSize()`, where we brutally change the batch size of an existing instance.

If that assumption is correct, I'd suggest replacing this code with something like:

```suggestion
		public ProxyConnection withBatchSize(int batchSize) {
		  ReactiveConnection reactiveConnection = connectionFuture.getNow( null );
		  if (reactiveConnection != null) {
			// Common case (hopefully): connection was already opened,
			// we can let callers use the delegate going forward and forget about the proxy.
		    return reactiveConnection.withBatchSize(batchSize);
		  }
		  else {
			// Uncommon case (hopefully): connection wasn't opened yet,
			// we will ask callers to use a new proxy that wraps the connection.
			return new ProxyConnection( () -> connectionSupplier.get().withBatchSize( batchSize ) );
		  }
		}
```

NOTE: If you add something to mark the proxy as closed (see my comment on `close`), it would be a good idea mark the current proxy as closed in the `else` block here, just in case someone (incorrectly) goes against the assumption that I stated above.

File: hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/SqlClientPool.java [hunk 5]
```diff
@@ -373,8 +402,8 @@ public CompletionStage<Void> executeBatch() {
 
 		@Override
 		public CompletionStage<Void> close() {
-			return connection != null
-					? connection.close().thenAccept( v -> connection = null )
+			return opened
+					? connectionFuture.getNow( null ).close()
 					: voidFuture();
```
Comment (yrodiere) [inline hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/SqlClientPool.java:430]: Shouldn't we remember that `close` was called in the proxy, so that if another method is called on the proxy, we don't mistakenly create the delegate?

I'm talking about the second case in particular:

1. Create connection proxy
2. Call close(): nothing happens
3. Call`execute(...)`: delegate gets created! Instead of erroring out.

File: hibernate-reactive-core/src/test/java/org/hibernate/reactive/MultithreadedInsertionWithLazyConnectionTest.java [hunk 6]
```diff
@@ -197,8 +197,13 @@ private CompletionStage<Void> storeEntity(Stage.Session s) {
 			final EntityWithGeneratedId entity = new EntityWithGeneratedId();
 			entity.name = beforeOperationThread + "__" + localVerticleOperationSequence;
 
+			// We are not using transactions on purpose here, because this approach will cause a context switch
+			// and an assertion error if things aren't handled correctly. See Hibernate Reactive issue #2768:
+			// https://github.com/hibernate/hibernate-reactive/issues/2768
```
Comment (yrodiere) [inline hibernate-reactive-core/src/test/java/org/hibernate/reactive/MultithreadedInsertionWithLazyConnectionTest.java]: Would it make sense to duplicate the test, to _also_ test the "transaction" case?

File: hibernate-reactive-core/src/main/java/org/hibernate/reactive/id/impl/BlockingIdentifierGenerator.java [hunk 7]
```diff
@@ -137,35 +134,38 @@ public Task execute(GeneratorState state) {
...
+						}
+						else {
+							//We ignore the state argument as we actually use the field directly
+							//for convenience, but they are the same object.
+							executor.submit( stateIgnored -> {
+								result.complete( next( newlyGeneratedHi ) );
+								return null;
+							} );
+						}
+					} );
```
Comment (yrodiere) [inline hibernate-reactive-core/src/main/java/org/hibernate/reactive/id/impl/BlockingIdentifierGenerator.java]: Are we sure `nextHiValue` will never throw an exception? I mean the method, not the future it returns.

Because if it does throw an exception, the `whenComplete` call here will be skipped and the operation will hang forever from the user's point of view.

File: hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/SqlClientPool.java (hunk 3 above)
Comment (tsegismont) [reply hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/SqlClientPool.java:241]: The idea was that, since the application will create a lot of these objects during its lifetime, it would be better to store a simple `boolean` field in `ProxyConnection` instead of a complete object (own headers + field).

@franz1981 would you recommend against it?

File: hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/SqlClientPool.java (hunk 2 above)
Comment (DavideD) [reply hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/SqlClientPool.java]: I wasn't 100% sure about it either. 
Let's remove it for now, I left it in a separate commit for this reason.

File: hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/SqlClientPool.java (hunk 3 above)
Comment (DavideD) [reply hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/SqlClientPool.java:241]: > In any case, back to your question @DavideD: this kind of "reflection" in a `static` block should generally be fine in Quarkus even with native compilation, because it's executed during static init, before native compilation. If I turn out to be wrong, we'll improvise :)

Thanks, that's all I needed in writing :D

File: hibernate-reactive-core/src/test/java/org/hibernate/reactive/MultithreadedInsertionWithLazyConnectionTest.java (hunk 6 above)
Comment (DavideD) [reply hibernate-reactive-core/src/test/java/org/hibernate/reactive/MultithreadedInsertionWithLazyConnectionTest.java]: Yeah, it makes sense.

File: hibernate-reactive-core/src/main/java/org/hibernate/reactive/common/InternalStateAssertions.java (hunk 1 above)
Comment (DavideD) [reply hibernate-reactive-core/src/main/java/org/hibernate/reactive/common/InternalStateAssertions.java]: I don't know :)

Seems like it, but I feel that this PR is complicated enough. I will look into it as soon as we merge this.

File: hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/SqlClientPool.java (hunk 4 above)
Comment (DavideD) [reply hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/SqlClientPool.java]: Could you review [this commit](https://github.com/hibernate/hibernate-reactive/pull/2793/commits/5c245f90b1d3e2a270b0dcc22f09380e124c0275), please? Thanks

File: hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/SqlClientPool.java [hunk 8]
```diff
@@ -355,15 +399,22 @@ public CompletionStage<Void> rollbackTransaction() {
...
 		public ReactiveConnection withBatchSize(int batchSize) {
-			if ( connection == null ) {
-				this.batchSize = batchSize;
+			if ( closed ) {
+				throw LOG.connectionIsClosed();
+			}
+
+			if ( connectionFuture.isDone() ) {
+				// connection exists, we can let callers use the delegate and forget about the proxy.
+				return connectionFuture.getNow( null ).withBatchSize( batchSize );
```
Comment (yrodiere) [inline hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/SqlClientPool.java:409]: Note the pattern `if ( ... .isDone() ) { get() }` should be avoided in general, because it's sensitive to [TOCTOU](https://en.wikipedia.org/wiki/Time-of-check_to_time-of-use). That's why I suggested `var value = getNow(null); if ( value != null)` .

Though in this case... I think the worst that could happen is a missed opportunity, so it's probably fine.

File: hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/SqlClientPool.java [hunk 9]
```diff
@@ -355,15 +399,22 @@ public CompletionStage<Void> rollbackTransaction() {
...
 			}
 			else {
-				connection = connection.withBatchSize( batchSize );
+				return new ProxyConnection( () -> opened
```
Comment (yrodiere) [inline hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/SqlClientPool.java:412]: So the `opened` check here is supposed to handle a case where someone does something like this?

```
<trigger connection request>
connection = connection.withBatchSize(...); // Connection not yet initialized somehow?
connection.doSomething();
```

That seems odd... did you do this because you noticed it actually happening?

In any case, +1 to be on the safe side.

File: hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/SqlClientPool.java (hunk 4 above)
Comment (yrodiere) [reply hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/SqlClientPool.java]: I assume you meant https://github.com/hibernate/hibernate-reactive/pull/2793/commits/6b8a2f19d0704fe41643b9538e0efcffe1c1b0bd ?

File: hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/SqlClientPool.java (hunk 9 above)
Comment (DavideD) [reply hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/SqlClientPool.java:412]: It's to be on the safe side. 

Looking at the code, it seems to me there's a small window between setting `opened` to `true` and completing `completableFuture` with the connection. So, if `opened` it's true and `completableFuture` is not done, `.getNow(null)` will return `null` (and cause a `NullPointerException`), even if the connection is getting opened.

File: hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/SqlClientPool.java (hunk 8 above)
Comment (DavideD) [reply hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/SqlClientPool.java:409]: What I'm afraid of using `getNow(null)` in this case, it's that we will return null a bit too soon.

In this specific case, when `.isDone()` returns true, we should know for a fact that there's a result that we can return.

When it returns `false`, it's possible that by the time we call `.getNow(null)`, the result is not null and we have created a `ProxyConnection` even if we didn't need to, but my guess is that this use case won't happen often.

Comment (DavideD) [reply hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/SqlClientPool.java:409]: > Though in this case... I think the worst that could happen is a missed opportunity, so it's probably fine.

I didn't notice this line. Yes, that's what I was thinking.
The initial solution could have potentially caused a `NullPointerException` instead.

File: hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/SqlClientPool.java (hunk 9 above)
Comment (DavideD) [reply hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/SqlClientPool.java:412]: It's a bit late, I think I will sleep over it and merge it tomorrow morning if there are no other comments.
After that I will start the release.

Thanks
