### PR TITLE
implemented reactiveForceFlush() to fix UnsupportedOperationException

### LINKED ISSUE #1379: Non-reactive forceFlush in AbstractReactiveSaveEventListener.java:172
[There](https://github.com/hibernate/hibernate-reactive/blob/main/hibernate-reactive-core/src/main/java/org/hibernate/reactive/event/impl/AbstractReactiveSaveEventListener.java#L172) is a call to non-reactive forceFlush of `SessionImpl` that leads to UnsupportedOperationException from DefaultReactiveFlushEventListener:

```
	Caused by: java.util.concurrent.CompletionException: javax.persistence.PersistenceException: org.hibernate.HibernateException: java.lang.UnsupportedOperationException
		at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
		at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1194)
		at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2309)
		at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:144)
		at org.hibernate.reactive.event.impl.AbstractReactiveSaveEventListener.reactiveSaveWithGeneratedId(AbstractReactiveSaveEventListener.java:123)
		at org.hibernate.reactive.event.impl.DefaultReactiveMergeEventListener.saveTransientEntity(DefaultReactiveMergeEventListener.java:283)
		at org.hibernate.reactive.event.impl.DefaultReactiveMergeEventListener.lambda$entityIsTransient$5(DefaultReactiveMergeEventListener.java:257)
		at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1187)
		at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2309)
		at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:144)
		at org.hibernate.reactive.event.impl.DefaultReactiveMergeEventListener.entityIsTransient(DefaultReactiveMergeEventListener.java:257)
		at org.hibernate.reactive.event.impl.DefaultReactiveMergeEventListener.lambda$entityIsDetached$11(DefaultReactiveMergeEventListener.java:364)
		at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1187)
		at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2309)
		at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:144)
		at org.hibernate.reactive.event.impl.DefaultReactiveMergeEventListener.entityIsDetached(DefaultReactiveMergeEventListener.java:321)
		at org.hibernate.reactive.event.impl.DefaultReactiveMergeEventListener.reactiveOnMerge(DefaultReactiveMergeEventListener.java:190)
		at org.hibernate.reactive.event.impl.DefaultReactiveMergeEventListener.reactiveOnMerge(DefaultReactiveMergeEventListener.java:90)
		at org.hibernate.event.service.internal.EventListenerGroupImpl.lambda$fireEventOnEachListener$0(EventListenerGroupImpl.java:133)
		at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1187)
		at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2309)
		at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:144)
		at org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventListenerGroupImpl.java:133)
		at org.hibernate.reactive.session.impl.ReactiveSessionImpl.fireMerge(ReactiveSessionImpl.java:849)
		... 298 more
	Caused by: javax.persistence.PersistenceException: org.hibernate.HibernateException: java.lang.UnsupportedOperationException
		at app//org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:154)
		at app//org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:181)
		at app//org.hibernate.reactive.session.impl.ReactiveExceptionConverter.convert(ReactiveExceptionConverter.java:31)
		at app//org.hibernate.internal.SessionImpl.doFlush(SessionImpl.java:1411)
		at app//org.hibernate.internal.SessionImpl.forceFlush(SessionImpl.java:1438)
		at app//org.hibernate.reactive.event.impl.AbstractReactiveSaveEventListener.reactivePerformSave(AbstractReactiveSaveEventListener.java:172)
		at app//org.hibernate.reactive.event.impl.AbstractReactiveSaveEventListener.lambda$reactiveSaveWithGeneratedId$0(AbstractReactiveSaveEventListener.java:123)
		at java.base@17.0.1/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1187)
		... 320 more
	Caused by: org.hibernate.HibernateException: java.lang.UnsupportedOperationException
		... 326 more
	Caused by: java.lang.UnsupportedOperationException
		at org.hibernate.reactive.event.impl.DefaultReactiveFlushEventListener.onFlush(DefaultReactiveFlushEventListener.java:63)
		at org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventListenerGroupImpl.java:107)
		at org.hibernate.internal.SessionImpl.doFlush(SessionImpl.java:1407)
		... 324 more
```

### PR DESCRIPTION
**Pull request by blafond**
fixes #1379

### CODE REVIEW

File: hibernate-reactive-core/src/main/java/org/hibernate/reactive/event/impl/AbstractReactiveSaveEventListener.java [hunk 1]
```diff
@@ -162,34 +163,44 @@ protected CompletionStage<Void> reactivePerformSave(
...
+			return reactivePerformSaveOrReplicate(
+				entity,
+				key,
+				persister,
+				useIdentityColumn,
+				context,
+				source,
+				requiresImmediateIdAccess );
+		} );
+	}
```
Comment (gavinking) [inline hibernate-reactive-core/src/main/java/org/hibernate/reactive/event/impl/AbstractReactiveSaveEventListener.java:179]: IMO, this flow is just slightly convoluted. I would prefer to use something like:

```java
CompletionStage<EntityKey> key = !useIdentityColumn
        ? generateEntityKey( entity, id, persister, useIdentityColumn, source ).thenAccept( key -> persister.setIdentifier( entity, id, source ) )
        : CompletionStages.nullFuture();
return key.thenCompose( key -> reactivePerformSaveOrReplicate(
 				entity,
 				key,
 				persister,
 				useIdentityColumn,
 				context,
 				source,
 				requiresImmediateIdAccess ) );

```

That's simpler and clearer IMO.

**Review by gavinking — CHANGES_REQUESTED** [review]

File: hibernate-reactive-core/src/main/java/org/hibernate/reactive/event/impl/AbstractReactiveSaveEventListener.java (hunk 1 above)
Comment (gavinking) [reply hibernate-reactive-core/src/main/java/org/hibernate/reactive/event/impl/AbstractReactiveSaveEventListener.java:179]: (And then the logic in `generateEntityKey()` can also be simplified.

Comment (blafond) [reply hibernate-reactive-core/src/main/java/org/hibernate/reactive/event/impl/AbstractReactiveSaveEventListener.java:179]: I ran with your version and ended up with the following that works too with basically the same #lines of code. I prefer the first version (after removing the redundant `useIdentityColumn` parameter in `generateEntityKey(...)`)

... and I could live with either.
```
	protected CompletionStage<Void> reactivePerformSave(
			Object entity,
			Serializable id,
			EntityPersister persister,
			boolean useIdentityColumn,
			C context,
			EventSource source,
			boolean requiresImmediateIdAccess) {

		if ( LOG.isTraceEnabled() ) {
			LOG.tracev( "Saving {0}", infoString( persister, id, source.getFactory() ) );
		}

		CompletionStage<EntityKey> key = useIdentityColumn
				? CompletionStages.nullFuture()
				: generateEntityKey( id, persister, source ).thenCompose( generatedKey -> {
			persister.setIdentifier( entity, id, source );
			return CompletionStages.completedFuture( generatedKey );
		} );

		return key.thenCompose( v -> {
			try {
				return reactivePerformSaveOrReplicate(
						entity,
						key.toCompletableFuture().get(),
						persister,
						useIdentityColumn,
						context,
						source,
						requiresImmediateIdAccess
				);
			}
			catch (Exception e) {
				return failedFuture( e );
			}
		} );
	}

	private CompletionStage<EntityKey> generateEntityKey(Serializable id, EntityPersister persister, EventSource source) {
		final EntityKey key = source.generateEntityKey( id, persister );
		final PersistenceContext persistenceContext = source.getPersistenceContextInternal();
		Object old = persistenceContext.getEntity( key );
		if ( old != null ) {
			if ( persistenceContext.getEntry( old ).getStatus() == Status.DELETED ) {
				return source.unwrap( ReactiveSession.class ).reactiveForceFlush(
						persistenceContext.getEntry( old ) ).thenApply( v -> key );
			}
			else {
				return failedFuture( new NonUniqueObjectException( id, persister.getEntityName() ) );
			}
		}

		return CompletionStages.completedFuture( key );
	}
```

Comment (gavinking) [reply hibernate-reactive-core/src/main/java/org/hibernate/reactive/event/impl/AbstractReactiveSaveEventListener.java:179]: I think theres two things wrong there:

- you use `thenCompose()` instead of `thenAccept()` which is redundant, and bad style, and
- I'm not sure what the point of the try/catch is ... the method you're calling wouldn't throw exceptions synchronously so there's nothing to catch.

Comment (gavinking) [reply hibernate-reactive-core/src/main/java/org/hibernate/reactive/event/impl/AbstractReactiveSaveEventListener.java:179]: (So if you eliminate the try/catch, and use `thenAccept()` then both those lambdas can be turned into one-line lambdas.)

Comment (DavideD) [reply hibernate-reactive-core/src/main/java/org/hibernate/reactive/event/impl/AbstractReactiveSaveEventListener.java:179]: You can use `thenApply`:
```
CompletionStage<EntityKey> key = useIdentityColumn
				? CompletionStages.nullFuture()
				: generateEntityKey( id, persister, source ).thenApply generatedKey -> {
			persister.setIdentifier( entity, id, source );
			return generatedKey;
		} );
```

Comment (DavideD) [reply hibernate-reactive-core/src/main/java/org/hibernate/reactive/event/impl/AbstractReactiveSaveEventListener.java:179]: You don't need the try-catch:
```
return key.thenCompose( entityKey -> reactivePerformSaveOrReplicate(
 		entity,
 		entityKey,
 		persister,
 		useIdentityColumn,
 		context,
 		source,
 		requiresImmediateIdAccess 
) );
```

**Review by DavideD — CHANGES_REQUESTED** [review]

File: hibernate-reactive-core/src/main/java/org/hibernate/reactive/event/impl/AbstractReactiveSaveEventListener.java (hunk 1 above)
Comment (blafond) [reply hibernate-reactive-core/src/main/java/org/hibernate/reactive/event/impl/AbstractReactiveSaveEventListener.java:180]: fixed
