### PR TITLE
Changes after ORM 5.4.22

### LINKED ISSUE #374: lazy collections and bytecode enhancer
So I've run into what I consider to be some pretty unexpected behavior of Hibernate ORM when the bytecode enhancer is enabled with `enableLazyInitialization = true`.

There's two aspects of the behavior that, naïvely, look suboptimal to me, at least in the context of HR:

1. By default, lazy collection are marked for field-level lazy fetching. I gotta say I just don't see much advantage to this, how is it better than the collection proxy? Indeed, it's arguably worse, since direct field access doesn't get intercepted. That's tolerable for fields that the user has *explicitly* marked for lazy fetching, but not for this *implicit* behavior.
2. When you *do* fetch the collection, `AbstractEntityPersister.initializeLazyProperty()` doesn't set the field of the entity like what it does for other lazy fields. That's either a bug, or it's due to how we're calling this method in Hibernate reactive. Whatever, it means that `AbstractEntityPersister.initializeLazyProperty()` has a pretty fragile contract.

@Sanne I know you're an expert on this stuff, can you help me understand all this please?

### PR DESCRIPTION
**Pull request by gavinking**
After the update to 5.4.22, the following changes can be made:

- put collections in default fetch group
- let ORM core do the logger syntax highlighting

Fixes #374.

### CODE REVIEW

File: hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/SqlClientConnection.java [hunk 1]
```diff
@@ -36,27 +33,21 @@
...
-	private final boolean formatSQL;
-	private final boolean highlightSQL;
+	private final SqlStatementLogger sqlStatementLogger;
 	private final boolean usePostgresStyleParameters;
 
 	private final Pool pool;
 	private final SqlConnection connection;
 	private Transaction transaction;
 
 	SqlClientConnection(SqlConnection connection, Pool pool,
```
Comment (DavideD) [inline hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/SqlClientConnection.java:45]: @Sanne This might affect what you where doing for Quarkus

Comment (gavinking) [reply hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/SqlClientConnection.java:45]: It shouldn't, I don't think.

Comment (DavideD) [reply hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/SqlClientConnection.java:45]: The class that in Quarkus extends the SqlClientPool needed some refactoring and these properties were a bit problematic when I talked to him about it. This PR might make things easier.

Anyway, I don't think this is a blocking issue for us. I just wanted the mentioned that this part is changing to him.

Comment (gavinking) [reply hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/SqlClientConnection.java:45]: Yeah, but this is a change that's completely *internal* to `SqlClientPool`.

Comment (DavideD) [reply hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/SqlClientConnection.java:45]: Sure, ok

**Comment by DavideD** [comment]
LGTM

File: hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/SqlClientConnection.java (hunk 1 above)
Comment (Sanne) [reply hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/SqlClientConnection.java:45]: Thanks, yes this is useful to know.
