### PR TITLE
[#479] Test exception when sharing session between contexts

### LINKED ISSUE #479: error when user shares session between multiple vert.x contexts
It's currently considered an error to share a `Session` between multiple reactive streams, so we should detect that condition and throw an exception.

It seems that the best we to detect the condition is to look at the vert.x context.

### PR DESCRIPTION
**Pull request by DavideD**
Resolves #479 
  
It's currently considered an error to share a Session between
multiple reactive streams, so we should detect that condition
and throw an exception.

### CODE REVIEW

File: hibernate-reactive-core/src/test/java/org/hibernate/reactive/MultipleContextTest.java [hunk 1]
```diff
@@ -0,0 +1,146 @@
...
+import io.vertx.ext.unit.TestContext;
+import org.assertj.core.api.Assertions;
+
+/**
+ * It's currently considered an error to share a Session between multiple reactive streams,
+ * so we should detect that condition and throw an exception.
+ */
+public class MultipleContextTest extends BaseReactiveTest {
+
+	private static final String ERROR_MESSAGE = "Detected use of the Reactive Session from a different Thread than the one which was used to open the Reactive Session - this suggests an invalid integration;";
```
Comment (gavinking) [inline hibernate-reactive-core/src/test/java/org/hibernate/reactive/MultipleContextTest.java:30]: What's the ; for?

Comment (gavinking) [reply hibernate-reactive-core/src/test/java/org/hibernate/reactive/MultipleContextTest.java:30]: Also, "Reactive" should be lowercase, since it's not a type or a proper noun.

Comment (DavideD) [reply hibernate-reactive-core/src/test/java/org/hibernate/reactive/MultipleContextTest.java]: The error message is longer than the string I use here and contains a semicolon. I've update the assert to check a shorter version of the string.

I've also replaced 'Reactive' with 'reactive'

Comment (gavinking) [reply hibernate-reactive-core/src/test/java/org/hibernate/reactive/MultipleContextTest.java]: Thanks!

**Comment by DavideD** [comment]
Resolves #479 

Thanks
