### PR TITLE
Terrible error reporting when JDBC scheme is not recognized #2478

### LINKED ISSUE #2478: terrible error reporting when JDBC scheme is not recognized
If I set:

    jakarta.persistence.jdbc.url=jdbc:h2:~/h2temp

I get the following extremely unhelpful error:

```
Unable to create requested service [org.hibernate.engine.jdbc.env.spi.JdbcEnvironment] due to: Cannot invoke "io.vertx.sqlclient.Pool.getConnection()" because "pool" is null
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.createService(AbstractServiceRegistryImpl.java:275)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:237)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:214)
	at org.hibernate.reactive.provider.impl.ReactiveTypeContributor.dialect(ReactiveTypeContributor.java:116)
	at org.hibernate.reactive.provider.impl.ReactiveTypeContributor.registerReactiveChanges(ReactiveTypeContributor.java:80)
	at org.hibernate.reactive.provider.impl.ReactiveTypeContributor.contribute(ReactiveTypeContributor.java:75)
	at org.hibernate.boot.internal.MetadataBuilderImpl.applyTypes(MetadataBuilderImpl.java:293)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1116)
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.applyTypeContributors(EntityManagerFactoryBuilderImpl.java:1383)
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.applyMetamodelBuilderSettings(EntityManagerFactoryBuilderImpl.java:1361)
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.<init>(EntityManagerFactoryBuilderImpl.java:236)
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.<init>(EntityManagerFactoryBuilderImpl.java:173)
	at org.hibernate.reactive.provider.impl.ReactiveEntityManagerFactoryBuilder.<init>(ReactiveEntityManagerFactoryBuilder.java:34)
	at org.hibernate.reactive.provider.ReactivePersistenceProvider.getEntityManagerFactoryBuilder(ReactivePersistenceProvider.java:168)
	at org.hibernate.reactive.provider.ReactivePersistenceProvider.getEntityManagerFactoryBuilderOrNull(ReactivePersistenceProvider.java:101)
	at org.hibernate.reactive.provider.ReactivePersistenceProvider.createEntityManagerFactory(ReactivePersistenceProvider.java:59)
	at jakarta.persistence.Persistence.createEntityManagerFactory(Persistence.java:90)
	at jakarta.persistence.Persistence.createEntityManagerFactory(Persistence.java:66)
	at org.hibernate.reactive.example.session.Main.main(Main.java:38)
```

I'm almost certain this is a regression, and that we used to report such problems in a much better way.

I notice that the following two methods of `Log` no longer have any callers:

```java
	@Message(id = 48, value = "Could not determine Dialect from JDBC driver metadata (specify a connection URI with scheme 'postgresql:', 'mysql:', 'cockroachdb', or 'db2:')")
	HibernateException couldNotDetermineDialectFromJdbcDriverMetadata();

	@Message(id = 49, value = "Could not determine Dialect from connection URI: '%1$s' (specify a connection URI with scheme 'postgresql:', 'mysql:', 'cockroachdb', or 'db2:')")
	HibernateException couldNotDetermineDialectFromConnectionURI(String url);
```

### PR DESCRIPTION
**Pull request by dreab8**
Fix #2478

### CODE REVIEW

File: hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/DefaultSqlClientPoolConfiguration.java [hunk 1]
```diff
@@ -90,12 +90,17 @@ public PoolOptions poolOptions() {
 
 	@Override
 	public SqlConnectOptions connectOptions(URI uri) {
-		String scheme = uri.getScheme();
-		String path = scheme.equals( "oracle" )
+		final String scheme = uri.getScheme();
+		if ( !isSchemeSupported( scheme ) ) {
+			throw new IllegalArgumentException( "Unsupported URI scheme: " + scheme + " for uri:" + uri
+														+ "; supported schemes are 'postgresql', 'postgres', 'mariadb', 'mysql', 'db2', 'cockroachdb', 'sqlserver', 'oracle' ");
```
Comment (DavideD) [inline hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/DefaultSqlClientPoolConfiguration.java]: Shouldn't this go in the Log interface with an error code?

Comment (DavideD) [reply hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/DefaultSqlClientPoolConfiguration.java]: Actually, why don't you call the existing methods (or something similar)?
```
	@Message(id = 48, value = "Could not determine Dialect from JDBC driver metadata (specify a connection URI with scheme 'postgresql:', 'mysql:', 'cockroachdb', or 'db2:')")
	HibernateException couldNotDetermineDialectFromJdbcDriverMetadata();

	@Message(id = 49, value = "Could not determine Dialect from connection URI: '%1$s' (specify a connection URI with scheme 'postgresql:', 'mysql:', 'cockroachdb', or 'db2:')")
	HibernateException couldNotDetermineDialectFromConnectionURI(String url);
```

File: hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/DefaultSqlClientPoolConfiguration.java [hunk 2]
```diff
@@ -385,4 +390,11 @@ private int defaultPort(String scheme) {
 		}
 	}
 
+	private boolean isSchemeSupported(String scheme) {
+		return switch ( scheme ) {
+			case "postgresql", "postgres", "mariadb", "mysql", "db2", "cockroachdb", "sqlserver", "oracle" -> true;
```
Comment (DavideD) [inline hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/DefaultSqlClientPoolConfiguration.java:394]: I don't know, this to me seems overcomplicated, why don't you have a list of valid schemes?

For example:
```java
private static final List<String> SUPPORTED_SCHEMES = List.of("postgresql", "postgres", "mariadb", "mysql", "db2", "cockroachdb", "sqlserver", "oracle");

if ( !SUPPORTED_SCHEMES.contains( scheme ) ) {
   throw new IllegalArgumentException( "... valid schemes are: " + SUPPORTED_SCHEMES)
}
```

File: hibernate-reactive-core/src/test/java/org/hibernate/reactive/WrongJdbcUrlShemeTest.java [hunk 3]
```diff
@@ -0,0 +1,51 @@
...
+	@Test
+	public void testWithTransaction(VertxTestContext context) {
+		test( context, assertThrown( ServiceException.class, setupSessionFactory( this::constructConfiguration ) )
+				.thenAccept( WrongJdbcUrlShemeTest::assertException )
+		);
+	}
+
+	private static void assertException(Throwable throwable) {
+		assertThat( throwable.getMessage() )
+				.contains( "Unsupported URI scheme:" );
```
Comment (DavideD) [inline hibernate-reactive-core/src/test/java/org/hibernate/reactive/WrongJdbcUrlShemeTest.java]: If you throw the exception from our logger interface, you can check the error code here.

File: hibernate-reactive-core/src/main/java/org/hibernate/reactive/provider/service/NoJdbcEnvironmentInitiator.java [hunk 4]
```diff
@@ -84,7 +85,7 @@ protected JdbcEnvironmentImpl getJdbcEnvironmentUsingJdbcMetadata(
 			Integer explicitDatabaseMajorVersion,
 			Integer explicitDatabaseMinorVersion,
 			String explicitDatabaseVersion) {
-		try {
+		if ( configurationValues.containsKey( ALLOW_METADATA_ON_BOOT ) ) {
```
Comment (DavideD) [inline hibernate-reactive-core/src/main/java/org/hibernate/reactive/provider/service/NoJdbcEnvironmentInitiator.java]: Is it correct for this change to be in the same commit, or it's just to align he code with ORM?

File: hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/DefaultSqlClientPoolConfiguration.java (hunk 2 above)
Comment (gavinking) [reply hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/DefaultSqlClientPoolConfiguration.java:394]: I don't know what you mean by this @DavideD. Your suggestion looks _more_ complicated than whet Andrea has.

Comment (DavideD) [reply hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/DefaultSqlClientPoolConfiguration.java:394]: Really? Ok, I don't want to argue over this. I guess we have a different opinion.

Comment (DavideD) [reply hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/DefaultSqlClientPoolConfiguration.java:394]: To clarify, I mean that we can leave the code as it is.

File: hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/DefaultSqlClientPoolConfiguration.java (hunk 1 above)
Comment (DavideD) [reply hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/DefaultSqlClientPoolConfiguration.java]: I guess we can also remove them if they are not used

File: hibernate-reactive-core/src/main/java/org/hibernate/reactive/provider/service/NoJdbcEnvironmentInitiator.java (hunk 4 above)
Comment (DavideD) [reply hibernate-reactive-core/src/main/java/org/hibernate/reactive/provider/service/NoJdbcEnvironmentInitiator.java]: Ah... I guess you needed this change to make it work with MSSQL server. Right?

Comment (dreab8) [reply hibernate-reactive-core/src/main/java/org/hibernate/reactive/provider/service/NoJdbcEnvironmentInitiator.java]: in this way it's easy is easier to manage the exception thrown by this block of operations

File: hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/DefaultSqlClientPoolConfiguration.java (hunk 1 above)
Comment (dreab8) [reply hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/DefaultSqlClientPoolConfiguration.java]: I didn't call the the existing methods because I think the messages don't give the info that may help to solve the problem

Comment (dreab8) [reply hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/DefaultSqlClientPoolConfiguration.java]: maybe I could use `couldNotDetermineDialectFromConnectionURI`

File: hibernate-reactive-core/src/main/java/org/hibernate/reactive/logging/impl/Log.java [hunk 5]
```diff
@@ -159,9 +159,6 @@ public interface Log extends BasicLogger {
 	@Message(id = 47, value = "Generated identifier smaller or equal to 0: %1$d")
 	HibernateException generatedIdentifierSmallerOrEqualThanZero(Long id);
 
-	@Message(id = 48, value = "Could not determine Dialect from JDBC driver metadata (specify a connection URI with scheme 'postgresql:', 'mysql:', 'cockroachdb', or 'db2:')")
-	HibernateException couldNotDetermineDialectFromJdbcDriverMetadata();
-
 	@Message(id = 49, value = "Could not determine Dialect from connection URI: '%1$s' (specify a connection URI with scheme 'postgresql:', 'mysql:', 'cockroachdb', or 'db2:')")
```
Comment (DavideD) [inline hibernate-reactive-core/src/main/java/org/hibernate/reactive/logging/impl/Log.java]: I think that the list of supported schemas in the error message is missing `postgres:`, `oracle:`, `sqlserver:`, and `mariadb:`

File: hibernate-reactive-core/src/test/java/org/hibernate/reactive/WrongJdbcUrlSchemeTest.java [hunk 6]
```diff
@@ -0,0 +1,51 @@
...
+	@Test
+	public void testWithTransaction(VertxTestContext context) {
+		test( context, assertThrown( ServiceException.class, setupSessionFactory( this::constructConfiguration ) )
+				.thenAccept( WrongJdbcUrlSchemeTest::assertException )
+		);
+	}
+
+	private static void assertException(Throwable throwable) {
+		assertThat( throwable.getMessage() )
+				.contains( "HR000049" );
```
Comment (DavideD) [inline hibernate-reactive-core/src/test/java/org/hibernate/reactive/WrongJdbcUrlSchemeTest.java]: Could you change this to
```java
		assertThat( throwable ).hasMessageContaining( "HR000049" );
```
please?

It will give us extra information about the exception thrown if something is wrong with the message

File: hibernate-reactive-core/src/main/java/org/hibernate/reactive/logging/impl/Log.java [hunk 7]
```diff
@@ -159,9 +159,6 @@ public interface Log extends BasicLogger {
...
 	HibernateException couldNotDetermineDialectFromConnectionURI(String url);
```
Comment (DavideD) [inline hibernate-reactive-core/src/main/java/org/hibernate/reactive/logging/impl/Log.java]: `JdbcUrlParserTest` expects an `IllegalArgumentException` and not an `HibernateException`.
I think it makes sense to return an `IllegalArgumentException` here.

**Comment by DavideD** [comment]
Thanks
