### PR TITLE
Fix getReference with Bytecode Enhancements

### LINKED ISSUE #1891: getReference fails with Bytecode Enahncements enabled
```
Caused by: org.hibernate.reactive.event.impl.UnexpectedAccessToTheDatabase: Unexpected access to the database
	at app//org.hibernate.reactive.event.impl.DefaultReactiveLoadEventListener.onLoad(DefaultReactiveLoadEventListener.java:112)
	at app//org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventListenerGroupImpl.java:138)
	at app//org.hibernate.internal.SessionImpl.fireLoadNoChecks(SessionImpl.java:1225)
	at app//org.hibernate.internal.SessionImpl.fireLoad(SessionImpl.java:1213)
	at app//org.hibernate.loader.internal.IdentifierLoadAccessImpl.getReference(IdentifierLoadAccessImpl.java:185)
	at app//org.hibernate.loader.internal.IdentifierLoadAccessImpl.doGetReference(IdentifierLoadAccessImpl.java:131)
	at app//org.hibernate.loader.internal.IdentifierLoadAccessImpl.lambda$getReference$0(IdentifierLoadAccessImpl.java:88)
	at app//org.hibernate.loader.internal.IdentifierLoadAccessImpl.perform(IdentifierLoadAccessImpl.java:112)
	at app//org.hibernate.loader.internal.IdentifierLoadAccessImpl.getReference(IdentifierLoadAccessImpl.java:88)
	at app//org.hibernate.internal.SessionImpl.getReference(SessionImpl.java:2535)
```

### PR DESCRIPTION
**Pull request by DavideD**
Fix #1891

### CODE REVIEW

File: hibernate-reactive-core/src/main/java/org/hibernate/reactive/event/impl/DefaultReactiveLoadEventListener.java [hunk 1]
```diff
@@ -361,7 +361,7 @@ else if ( persister.getRepresentationStrategy().getProxyFactory() != null ) {
 			// we have a HibernateProxy factory, this case is more complicated
 			return loadWithProxyFactory( event, persister, keyToLoad );
 		}
-		else if ( !persister.hasSubclasses() ) {
+		else if ( persister.hasSubclasses() ) {
```
Comment (gavinking) [inline hibernate-reactive-core/src/main/java/org/hibernate/reactive/event/impl/DefaultReactiveLoadEventListener.java:364]: oops!

Comment (DavideD) [reply hibernate-reactive-core/src/main/java/org/hibernate/reactive/event/impl/DefaultReactiveLoadEventListener.java:364]: Yeah :)

It was correct for ORM 6.4, but good luck noticing that it needs to be changed for ORM 6.5 without the proper test
